@host = http://localhost:5153/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMzM0MjkyZi00OWFhLTRmYzQtYWIwOS1lZmJhODNkZThlODUiLCJuYW1lIjoiUmFwaGFlbCBSYW1pcmV6IiwianRpIjoiNWQxMzI1OTEtM2NlNy00NjJmLThlMDYtMTlhNGY3YzA4ZjY4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTY4MjA4NTg4OSwiaXNzIjoiSm9iQm9hcmRzIiwiYXVkIjoiSm9iQm9hcmRzIn0.95R_-KlSBDyghQ0XqLFDOYC8xXO9XOtkSneE4xdFpio
@jobCategoryId = d828185e-73ac-486b-ab06-8237da42997e

POST {{host}}/jobCategories/{{jobCategoryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Test",
	"description": "Hello there this is another updateseee"
}
