@host=http://localhost:5153/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMzM0MjkyZi00OWFhLTRmYzQtYWIwOS1lZmJhODNkZThlODUiLCJuYW1lIjoiUmFwaGFlbCBSYW1pcmV6IiwianRpIjoiOTE5NTIwYjItOWYzZi00NDc4LWE2MGYtYTI2ZmNkZDlhZGJkIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTY4MjAwNDk3OSwiaXNzIjoiSm9iQm9hcmRzIiwiYXVkIjoiSm9iQm9hcmRzIn0.dnY8JRn9z_VJTjhjmoJyOldQ7XzLqIz_bCjCwCQEs3w


POST {{host}}/Account/Profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fullName": "Raphael Ramirez"
}