@host=http://localhost:5153/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMzM0MjkyZi00OWFhLTRmYzQtYWIwOS1lZmJhODNkZThlODUiLCJuYW1lIjoiUmFwaGFlbCBSYW1pcmV6IiwianRpIjoiZGRjMjAyOWQtMDZhYS00Mzc2LThkMzgtYzIyNmMwODJmNjE5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTY4MjA3NDY2NSwiaXNzIjoiSm9iQm9hcmRzIiwiYXVkIjoiSm9iQm9hcmRzIn0.rg_kK9QvSHPC_uS-P99DWqbJTpS99reoHrVZanfHAF4

DELETE  {{host}}/JobSeekers/Resume
Content-Type: application/json
Authorization: Bearer {{token}}