@host=http://localhost:5153/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYjJjY2RlNC1mODU4LTRlZWEtYTRiYi01MDA1ZGM0Y2U2OWMiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImp0aSI6ImJjOTU0ZmFiLWZjNDEtNDZjYy1iMmQ2LWVhODNjZDJhNWUzYiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNjgyMDA5MzQzLCJpc3MiOiJKb2JCb2FyZHMiLCJhdWQiOiJKb2JCb2FyZHMifQ.VPFk39eBINiF3ypmc2wPcD0MLA0Ggo5jqTD2_lt8dKI

GET {{host}}/JobSeekers/Resume
Content-Type: application/json
Authorization: Bearer {{token}}