@host=http://localhost:5153/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTA2MGM5YS0xNDM5LTQwMmEtYTRlYi03MmM3YmExZTQ3NjciLCJuYW1lIjoiUmFwaGFlbCBSYW1pcmV6IiwianRpIjoiNzk0MWI2ODktNjY0Yi00MGI3LTkyMzUtZTVhMzFiYjM4N2EyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTY4MjI2MzQyOCwiaXNzIjoiSm9iQm9hcmRzIiwiYXVkIjoiSm9iQm9hcmRzIn0.93Q-Ea_FMho9NFqXWjfewCc0JuqZ8CmUfeQNTyYjxvI

GET {{host}}/JobSeekers/Resume
Content-Type: application/json
Authorization: Bearer {{token}}