@host=http://localhost:5153/api

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmYzODZlMi05NDQyLTRlMWYtYTU3My00NjE4MTY0OTlhMGQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImp0aSI6IjM5YjU4Y2NhLTgwNDctNGQzMC04NzM0LTMzZTcyZDFhYjA5ZiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNjgyMTc2NTYwLCJpc3MiOiJKb2JCb2FyZHMiLCJhdWQiOiJKb2JCb2FyZHMifQ.Idpr7f410_LYDqSOVxwfUiUxetGPcxmFxZbiHguWZYM

@id=9220e684-64d7-42a0-b738-8038e6d91289

DELETE   {{host}}/JobPosts/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}