@host=http://localhost:5153/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNDc4Y2M2OS1kNGQ1LTQzOWQtOWFkYi05ZTYzY2I1YTY3ZjciLCJuYW1lIjoiUmFwaGFlbCBSYW1pcmV6IiwianRpIjoiODMyZWMyNGEtZTk3Ny00YmM1LWEzYjUtMGU5ZmQ2NmMyMTI0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTY4MjI1MjI0OCwiaXNzIjoiSm9iQm9hcmRzIiwiYXVkIjoiSm9iQm9hcmRzIn0.uOz5wy1H76b3EFXQjzE0oGp20ETZBpVAfnYJcMTB29Q
@jobPostId=a2546e22-3884-4af6-845d-997aa31244c5


GET  {{host}}/JobPosts/{{jobPostId}}/myapplication
Content-Type: application/json
Authorization: Bearer {{token}}

